// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwWVwZPaOutRUaN3YGzq1amOj7vNGodmI',
    appId: '1:18927112924:web:bdfc1cd6e4c70711231a19',
    messagingSenderId: '18927112924',
    projectId: 'cacatalentosmobile2-2ffaf',
    authDomain: 'cacatalentosmobile2-2ffaf.firebaseapp.com',
    storageBucket: 'cacatalentosmobile2-2ffaf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWsjJRos7HG5hrXYGHqfIt1yaUUp_exIU',
    appId: '1:18927112924:android:f423dd3a2ee1e689231a19',
    messagingSenderId: '18927112924',
    projectId: 'cacatalentosmobile2-2ffaf',
    storageBucket: 'cacatalentosmobile2-2ffaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4-RUrURJrexdhC5ieDOZoJiEcIfM9cPc',
    appId: '1:18927112924:ios:f1a88fe0d22d159c231a19',
    messagingSenderId: '18927112924',
    projectId: 'cacatalentosmobile2-2ffaf',
    storageBucket: 'cacatalentosmobile2-2ffaf.appspot.com',
    iosClientId: '18927112924-t6l16m7p8hvdqk0ejh7fmv6o8n1tafob.apps.googleusercontent.com',
    iosBundleId: 'com.example.cacaTalentos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4-RUrURJrexdhC5ieDOZoJiEcIfM9cPc',
    appId: '1:18927112924:ios:f3102c9b44882653231a19',
    messagingSenderId: '18927112924',
    projectId: 'cacatalentosmobile2-2ffaf',
    storageBucket: 'cacatalentosmobile2-2ffaf.appspot.com',
    iosClientId: '18927112924-ce7btdct8oku01lidrkb3lkgmnu5td7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.cacaTalentos.RunnerTests',
  );
}
